#!/usr/bin/env node
// ============================================================================
//  Generate every secret a deployment needs (npm run secrets).
//
//    npm run secrets                  print KEY=value lines to paste into .env
//    npm run secrets -- --write       fill in the ones .env lacks (or has empty),
//                                     never touching a value that is already set
//    npm run secrets -- --env path    another env file (default ./.env)
//    npm run secrets -- --subject mailto:ops@example.com   VAPID contact
//
//  Values are URL-safe (POSTGRES_PASSWORD is spliced into DATABASE_URL by the
//  compose file) and generated with node:crypto; VAPID keys with web-push.
//
//  Rotation notes — why --write never overwrites:
//    STORAGE_URL_SECRET  signed private-file links stop working (they re-sign)
//    POSTGRES_PASSWORD   fixed into the database volume on first start;
//                        changing .env alone locks the app out
//    VAPID keys          every browser push subscription is invalidated
// ============================================================================

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const args = process.argv.slice(2);
const opt = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i === -1 ? fallback : args[i + 1];
};
const write = args.includes('--write');
const envPath = path.resolve(opt('env', '.env'));
const subject = opt('subject', 'mailto:admin@example.com');
if (!/^(mailto:|https:\/\/)/.test(subject)) {
  console.error('--subject must be a mailto: or https:// URL');
  process.exit(1);
}

const b64url = (bytes) => crypto.randomBytes(bytes).toString('base64url');
const hex = (bytes) => crypto.randomBytes(bytes).toString('hex');

async function vapid() {
  try {
    const { default: webpush } = await import('web-push');
    return webpush.generateVAPIDKeys();
  } catch {
    return null;   // web-push not installed (unusual): skip, say so below
  }
}

const keys = await vapid();
const secrets = [
  ['STORAGE_URL_SECRET', b64url(32), 'signs private-file URLs (required in production)'],
  ['ADMIN_TOKEN', b64url(32), 'maintenance + report triage endpoints'],
  ['METRICS_TOKEN', b64url(32), 'Bearer token for /metrics'],
  ['POSTGRES_PASSWORD', hex(24), 'compose PostgreSQL (fixed on the first start)'],
  ['TURN_SECRET', hex(32), 'coturn shared secret (compose `turn` profile)'],
  ['LIVEKIT_API_SECRET', hex(32), 'LiveKit key secret (compose `livekit` profile)'],
  ['GRAFANA_ADMIN_PASSWORD', b64url(18), 'Grafana admin (compose `observability` profile)'],
  ...(keys ? [
    ['VAPID_PUBLIC_KEY', keys.publicKey, 'Web Push'],
    ['VAPID_PRIVATE_KEY', keys.privateKey, 'Web Push (keep secret)'],
    ['VAPID_SUBJECT', subject, 'Web Push contact']
  ] : [])
];

if (!write) {
  console.log('# Generated by `npm run secrets` — paste into .env (only the ones you use).');
  // Comment on its own line: .env parsers differ on trailing "# …" after a value.
  for (const [name, value, why] of secrets) console.log(`# ${why}\n${name}=${value}`);
  if (!keys) console.log('# (web-push is not installed: run `npm ci` for VAPID keys)');
  process.exit(0);
}

// --write: fill gaps only. The development placeholders from .env.example
// count as gaps — they are public, so they are never a real secret.
const PLACEHOLDERS = new Set(['dev-insecure-storage-secret', 'change-me', 'change-me-too', 'secret']);
const shown = opt('env', '.env');
let existing = '';
try { existing = fs.readFileSync(envPath, 'utf8'); } catch (err) { if (err.code !== 'ENOENT') throw err; }
const current = new Map();
for (const line of existing.split('\n')) {
  const m = line.match(/^\s*([A-Z][A-Z0-9_]*)=(.*)$/);
  if (m) current.set(m[1], m[2].trim());
}

let text = existing;
const added = [];
for (const [name, value] of secrets) {
  if (current.get(name) && !PLACEHOLDERS.has(current.get(name))) continue;   // real value: keep
  if (current.has(name)) {
    // Present but empty (POSTGRES_PASSWORD= in .env.example) or the
    // development placeholder: replace in place.
    text = text.replace(new RegExp(`^(\\s*${name}=).*$`, 'm'), `$1${value}`);
  } else {
    if (!added.length) text = `${text.replace(/\n*$/, '\n')}\n# --- added by npm run secrets ---\n`;
    text += `${name}=${value}\n`;
  }
  added.push(name);
}
if (!added.length) {
  console.log(`${shown}: every secret is already set; nothing changed.`);
  process.exit(0);
}
fs.writeFileSync(envPath, text, { mode: 0o600 });
try { fs.chmodSync(envPath, 0o600); } catch { /* not supported (Windows) */ }
console.log(`${shown}: set ${added.join(', ')}.`);
console.log('Existing values were left untouched. Keep this file out of git and backups you share.');
